// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface GetCompteTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetCompteTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Type de compte recherché (ex. COURANT ou EPARGNE)
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * Type de compte recherché (ex. COURANT ou EPARGNE)
   * </pre>
   *
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();
}
